export const GET_HOT_DEAL_RESPONSE = "GET_HOT_DEAL_RESPONSE"
export const GET_HOT_DEAL_SUCCESS = "GET_HOT_DEAL_SUCCESS"
export const GET_HOT_DEAL_FAIL = "GET_HOT_DEAL_FAIL"


export const GET_PRODUCT_RESPONSE = "GET_PRODUCT_RESPONSE"
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS"
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL"



export const GET_PRODUCT_BY_ID_RESPONSE = "GET_PRODUCT_BY_ID_RESPONSE"
export const GET_PRODUCT_BY_ID_SUCCESS = "GET_PRODUCT_BY_ID_SUCCESS"
export const GET_PRODUCT_BY_ID_FAIL = "GET_PRODUCT_BY_ID_FAIL"

export const NEW_PRODUCT_RESPONSE = "NEW_PRODUCT_RESPONSE"
export const LOAD_MORE_PRODUCT = "LOAD_MORE_PRODUCT"
export const NEW_PRODUCT_SUCCESS = "NEW_PRODUCT_SUCCESS"
export const NEW_PRODUCT_FAIL = "NEW_PRODUCT_FAIL"
export const REMOVE_PRODUCT = "REMOVE_PRODUCT"

// delete product

export const DELETE_PRODUCT_RESPONSE = "DELETE_PRODUCT_RESPONSE"
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL"


// cart
export const ADD_TO_CART_RESPONSE = "ADD_TO_CART_RESPONSE"
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS"
export const ADD_TO_CART_FAIL = "ADD_TO_CART_BY_ID_FAIL"
export const INCREASE_COUNT = "INCREASE_COUNT"
export const DECREASE_COUNT = "DECREASE_COUNT"
export const DELETE_ITEM_FROM_CART = "DELETE_ITEM_FROM_CART"
export const CLOSE_CART_ALERT = "CLOSE_CART_ALERT"

export const TOTAL_CART_NO = "TOTAL_CART_NO"

// search
export const SEARCH_RESPONSE = "SEARCH_RESPONSE"
export const SEARCH_SUCCESS = "SEARCH_SUCCESS"
export const SEARCH_FAIL = "SEARCH_BY_ID_FAIL"




export const FILTER_WARES = "FILTER_WARES"
export const FILTER_SHOE = "FILTER_SHOE"