export const LOGIN_RESPONSE = "LOGIN_RESPONSE"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGOUT_USER = "LOGOUT_USER"

export const REGISTER_RESPONSE = "REGISTER_RESPONSE"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"